import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const universities = [
  'Akademia Górniczo-Hutnicza im. Stanisława Staszica w Krakowie',
  'Akademia Muzyczna im. Feliksa Nowowiejskiego w Bydgoszczy',
  'Akademia Humanistyczno-Ekonomiczna w Łodzi',
  'Akademia Muzyczna im. Ignacego Jana Paderewskiego w Poznaniu',
  'Akademia Muzyczna im. Karola Lipińskiego we Wrocławiu',
  'Akademia Muzyczna im. Karola Szymanowskiego w Katowicach',
  'Akademia Muzyczna im. Stanisława Moniuszki w Gdańsku',
  'Akademia Piotrkowska',
  'Akademia Polonijna w Częstochowie',
  'Akademia Sztuk Pięknych im. Eugeniusza Gepperta we Wrocławiu',
  'Akademia Sztuk Pięknych im. Jana Matejki w Krakowie',
  'Akademia Sztuk Pięknych im. Władysława Strzemińskiego w Łodzi',
  'Akademia Sztuk Pięknych w Gdańsku',
  'Akademia Sztuk Pięknych w Katowicach',
  'Akademia Sztuk Pięknych w Warszawie',
  'Akademia Sztuki w Szczecinie',
  'Akademia Teatralna im. Aleksandra Zelwerowicza w Warszawie',
  'Akademia Wychowania Fizycznego i Sportu im. Jędrzeja Śniadeckiego w Gdańsku',
  'Akademia Wychowania Fizycznego im. Eugeniusza Piaseckiego w Poznaniu',
  'Akademia Wychowania Fizycznego im. Jerzego Kukuczki w Katowicach',
  'Akademia Wychowania Fizycznego Józefa Piłsudskiego w Warszawie',
  'Biblioteka Narodowa',
  'Bielska Wyższa Szkoła im. Józefa Tyszkiewicza w Bielsku-Białej',
  'Bydgoska Szkoła Wyższa w Bydgoszczy',
  'CASE - Centrum Analiz Społeczno-Ekonomicznych - Fundacja Naukowa',
  'Centralny Instytut Analiz Polityczno-Prawnych',
  'Centralny Ośrodek Badawczo-Rozwojowy Przemysłu Izolacji Budowlanej',
  'Centrum Astronomiczne im. Mikołaja Kopernika Polskiej Akademii Nauk',
  'Centrum Badań i Innowacji Pro-Akademia',
  'Centrum Badań Kosmicznych Polskiej Akademii Nauk',
  'Centrum Badań Molekularnych i Makromolekularnych Polskiej Akademii Nauk',
  'Centrum Badawczo - Rozwojowe "NOVASOME" spółka z o.o.',
  'Centrum Fizyki Teoretycznej Polskiej Akademii Nauk',
  'Centrum Materiałów Polimerowych i Węglowych Polskiej Akademii Nauk',
  'Centrum Medycznego Kształcenia Podyplomowego',
  'Centrum Nauki Kopernik',
  'Centrum Naukowo-Badawcze Ochrony Przeciwpożarowej im. Józefa Tuliszkowskiego - Państwowy Instytut Badawczy',
  'Centrum Techniki Okrętowej S.A. Zakład Badawczo-Rozwojowy',
  'Chrześcijańska Akademia Teologiczna w Warszawie',
  'Collegium Civitas w Warszawie',
  'Collegium Masoviense - Wyższa Szkoła Nauk o Zdrowiu w Żyrardowie',
  'ENSEMBLE3 spółka z ograniczoną odpowiedzialnością',
  'Fundacja Naukowa Instytut Badań Strukturalnych',
  'Gdański Uniwersytet Medyczny',
  'Fundacja Rozwoju Kardiochirurgii im. prof. Zbigniewa Religi',
  'Górnośląska Wyższa Szkoła Przedsiębiorczości im. Karola Goduli w Chorzowie',
  'Instytut "Pomnik - Centrum Zdrowia Dziecka"',
  'Instytut Agrofizyki im. Bohdana Dobrzańskiego Polskiej Akademii Nauk',
  'Instytut Archeologii i Etnologii Polskiej Akademii Nauk',
  'Instytut Badań i Rozwoju Motoryzacji BOSMAL Sp. z o.o.',
  'Instytut Badań Literackich Polskiej Akademii Nauk',
  'Instytut Badań Systemowych Polskiej Akademii Nauk',
  'Instytut Badawczy Leśnictwa',
  'Instytut Biochemii i Biofizyki Polskiej Akademii Nauk',
  'Instytut Biocybernetyki i Inżynierii Biomedycznej im. Macieja Nałęcza Polskiej Akademii Nauk',
  'Instytut Biologii Doświadczalnej im. Marcelego Nenckiego Polskiej Akademii Nauk',
  'Instytut Biologii Medycznej Polskiej Akademii Nauk',
  'Instytut Biologii Ssaków Polskiej Akademii Nauk',
  'Instytut Botaniki im. Władysława Szafera Polskiej Akademii Nauk',
  'Instytut Budownictwa Wodnego Polskiej Akademii Nauk',
  'Instytut Chemii Bioorganicznej Polskiej Akademii Nauk',
  'Instytut Chemii Fizycznej Polskiej Akademii Nauk',
  'Instytut Chemii Organicznej Polskiej Akademii Nauk',
  'Instytut Dendrologii Polskiej Akademii Nauk',
  'Instytut Ekologii Terenów Uprzemysłowionych',
  'Instytut Ekspertyz Medycznych w Łodzi',
  'Instytut Filozofii i Socjologii Polskiej Akademii Nauk',
  'Instytut Fizjologii i Patologii Słuchu',
  'Instytut Fizjologii i Żywienia Zwierząt im. Jana Kielanowskiego Polskiej Akademii Nauk',
  'Instytut Fizjologii Roślin im. Franciszka Górskiego Polskiej Akademii Nauk',
  'Instytut Fizyki Jądrowej im. Henryka Niewodniczańskiego Polskiej Akademii Nauk',
  'Instytut Fizyki Molekularnej Polskiej Akademii Nauk',
  'Instytut Fizyki Polskiej Akademii Nauk',
  'Instytut Genetyki Człowieka Polskiej Akademii Nauk',
  'Instytut Genetyki Roślin Polskiej Akademii Nauk',
  'Instytut Geofizyki Polskiej Akademii Nauk',
  'Instytut Geografii i Przestrzennego Zagospodarowania im. Stanisława Leszczyckiego Polskiej Akademii Nauk',
  'Instytut Gospodarki Surowcami Mineralnymi i Energią Polskiej Akademii Nauk',
  'Instytut Immunologii i Terapii Doświadczalnej im. Ludwika Hirszfelda Polskiej Akademii Nauk',
  'Instytut Informatyki Teoretycznej i Stosowanej Polskiej Akademii Nauk',
  'Instytut Inżynierii Chemicznej Polskiej Akademii Nauk',
  'Instytut Języka Polskiego Polskiej Akademii Nauk',
  'Instytut Kultur Śródziemnomorskich i Orientalnych Polskiej Akademii Nauk',
  'Instytut Łączności - Państwowy Instytut Badawczy',
  'Instytut Maszyn Przepływowych im. Roberta Szewalskiego Polskiej Akademii Nauk',
  'Instytut Matematyczny Polskiej Akademii Nauk',
  'Instytut Matki i Dziecka',
  'Instytut Mechaniki Górotworu Polskiej Akademii Nauk',
  'Instytut Medycyny Doświadczalnej i Klinicznej im. Mirosława Mossakowskiego Polskiej Akademii Nauk',
  'Instytut Medycyny Pracy im. prof. dr. med. Jerzego Nofera',
  'Instytut Metalurgii i Inżynierii Materiałowej im. Aleksandra Krupkowskiego Polskiej Akademii Nauk',
  'Instytut Nauk Ekonomicznych Polskiej Akademii Nauk',
  'Instytut Nauk Geologicznych Polskiej Akademii Nauk',
  'Instytut Nauk Prawnych Polskiej Akademii Nauk',
  'Instytut Niskich Temperatur i Badań Strukturalnych im. Włodzimierza Trzebiatowskiego Polskiej Akademii Nauk',
  'Instytut Oceanologii Polskiej Akademii Nauk',
  'Instytut Ochrony Przyrody Polskiej Akademii Nauk',
  'Instytut Ochrony Roślin - Państwowy Instytut Badawczy',
  'Instytut Podstaw Informatyki Polskiej Akademii Nauk',
  'Instytut Podstaw Inżynierii Środowiska Polskiej Akademii Nauk',
  'Instytut Podstawowych Problemów Techniki Polskiej Akademii Nauk',
  'Instytut Psychiatrii i Neurologii',
  'Instytut Psychologii Polskiej Akademii Nauk',
  'Instytut Rozwoju Wsi i Rolnictwa Polskiej Akademii Nauk',
  'Instytut Statystyki Kościoła Katolickiego SAC',
  'Instytut Studiów Politycznych Polskiej Akademii Nauk',
  'Instytut Systematyki i Ewolucji Zwierząt Polskiej Akademii Nauk',
  'Instytut Sztuki Polskiej Akademii Nauk',
  'Instytut Śląski',
  'Instytut Środowiska Rolniczego i Leśnego Polskiej Akademii Nauk',
  'Instytut Techniczny Wojsk Lotniczych',
  'Instytut Technologii Bezpieczeństwa MORATEX',
  'Instytut Teologiczny im. św. Jana Kantego w Bielsku-Białej',
  'Instytut Uprawy Nawożenia i Gleboznawstwa - Państwowy Instytut Badawczy',
  'Instytut Wymiaru Sprawiedliwości',
  'Instytut Wysokich Ciśnień Polskiej Akademii Nauk',
  'Kaszubsko-Pomorska Szkoła Wyższa w Wejherowie',
  'Katolicki Uniwersytet Lubelski Jana Pawła II',
  'KGHM CUPRUM sp. z o.o. Centrum Badawczo-Rozwojowe',
  'Koszalińska Wyższa Szkoła Nauk Humanistycznych w Koszalinie',
  'Krakowska Wyższa Szkoła Promocji Zdrowia w Krakowie',
  'Lingwistyczna Szkoła Wyższa w Warszawie',
  'Lubelska Szkoła Wyższa w Rykach',
  'Małopolska Wyższa Szkoła Ekonomiczna z siedzibą w Tarnowie',
  'Międzynarodowy Instytut Biologii Molekularnej i Komórkowej w Warszawie',
  'Muzeum Archeologiczne w Poznaniu',
  'Muzeum Górnośląskie w Bytomiu',
  'Muzeum Historii Fotografii im. Walerego Rzewuskiego w Krakowie',
  'Muzeum Narodowe w Krakowie',
  'Muzeum Sztuki w Łodzi',
  'Muzeum Sztuki Współczesnej w Krakowie MOCAK',
  'Narodowy Instytut Leków',
  'Nazwa instytucji',
  'Niepubliczna Wyższa Szkoła Medyczna we Wrocławiu',
  'Ośrodek "Pamięć i Przyszłość"',
  'Ośrodek Badawczo-Rozwojowy Budowy Urządzeń Chemicznych CEBEA',
  'Państwowa Wyższa Szkoła Filmowa, Telewizyjna i Teatralna im. Leona Schillera w Łodzi',
  'Państwowy Instytut Geologiczny - Państwowy Instytut Badawczy',
  'Państwowy Instytut Medyczny Ministerstwa Spraw Wewnętrznych i Administracji',
  'Państwowy Instytut Weterynaryjny - Państwowy Instytut Badawczy',
  'Papieski Wydział Teologiczny we Wrocławiu',
  'Pedagogium Wyższa Szkoła Nauk Społecznych w Warszawie',
  'Podkarpacka Szkoła Wyższa im. bł. ks. Władysława Findysza w Jaśle',
  'Politechnika Białostocka',
  'Politechnika Częstochowska',
  'Politechnika Gdańska',
  'Politechnika Koszalińska',
  'Politechnika Krakowska im. Tadeusza Kościuszki',
  'Politechnika Lubelska',
  'Politechnika Łódzka',
  'Politechnika Opolska',
  'Politechnika Poznańska',
  'Politechnika Rzeszowska im. Ignacego Łukasiewicza',
  'Politechnika Śląska',
  'Politechnika Świętokrzyska',
  'Politechnika Warszawska',
  'Politechnika Wrocławska',
  'Polski Instytut Spraw Międzynarodowych',
  'Polski Instytut Studiów Nad Sztuką Świata',
  'Pomorska Szkoła Wyższa w Starogardzie Gdańskim',
  'Pomorska Wyższa Szkoła Nauk Stosowanych w Gdyni',
  'Pomorski Uniwersytet Medyczny w Szczecinie',
  'Powszechna Wyższa Szkoła Humanistyczna "Pomerania" w Chojnicach',
  'Poznańskie Towarzystwo Przyjaciół Nauk',
  'Prawosławne Seminarium Duchowne w Warszawie',
  'Publiczna Uczelnia Zawodowa w Grudziądzu',
  'Radomska Szkoła Wyższa',
  'Społeczna Akademia Nauk z siedzibą w Łodzi',
  'STER Instytut Maciej Szymański',
  'Stowarzyszenie Polska Platforma Bezpieczeństwa Wewnętrznego',
  'Szkoła Główna Gospodarstwa Wiejskiego w Warszawie',
  'Szkoła Główna Handlowa w Warszawie',
  'Szkoła Główna Krajowa z siedzibą w Warszawie',
  'Szkoła Główna Mikołaja Kopernika',
  'Szkoła Wyższa im. Bogdana Jańskiego w Warszawie',
  'Szkoła Wyższa im. Pawła Włodkowica w Płocku',
  'Szkoła Wyższa Rzemiosł Artystycznych i Zarządzania we Wrocławiu',
  'Śląska Wyższa Szkoła Medyczna w Katowicach',
  'Śląski Ogród Botaniczny',
  'Śląski Park Technologii Medycznych ŚPTM KMS Sp. z o.o.',
  'Śląski Uniwersytet Medyczny w Katowicach',
  'Świętokrzyskie Centrum Onkologii w Kielcach',
  'Uczelnia Łazarskiego w Warszawie',
  'Uczelnia Metropolitalna',
  'Uczelnia Nauk Społecznych',
  'Uniwersytet Ekonomiczny w Katowicach',
  'Uniwersytet Ekonomiczny w Krakowie',
  'Uniwersytet Ekonomiczny w Poznaniu',
  'Uniwersytet Ekonomiczny we Wrocławiu',
  'Uniwersytet Gdański',
  'Uniwersytet im. Adama Mickiewicza w Poznaniu',
  'Uniwersytet Jagielloński w Krakowie',
  'Uniwersytet Jana Kochanowskiego w Kielcach',
  'Uniwersytet Kardynała Stefana Wyszyńskiego w Warszawie',
  'Uniwersytet Kazimierza Wielkiego w Bydgoszczy',
  'Uniwersytet Łódzki',
  'Uniwersytet Marii Curie-Skłodowskiej w Lublinie',
  'Uniwersytet Medyczny im. Karola Marcinkowskiego w Poznaniu',
  'Uniwersytet Medyczny w Białymstoku',
  'Uniwersytet Medyczny w Lublinie',
  'Uniwersytet Medyczny w Łodzi',
  'Uniwersytet Mikołaja Kopernika w Toruniu',
  'Uniwersytet Muzyczny Fryderyka Chopina w Warszawie',
  'Uniwersytet Opolski',
  'Uniwersytet Papieski Jana Pawła II w Krakowie',
  'Uniwersytet Przyrodniczy w Lublinie',
  'Uniwersytet Przyrodniczy w Poznaniu',
  'Uniwersytet Przyrodniczy we Wrocławiu',
  'Uniwersytet Rolniczy im. Hugona Kołłątaja w Krakowie',
  'Uniwersytet Rzeszowski',
  'Uniwersytet Szczeciński',
  'Uniwersytet Śląski w Katowicach',
  'Uniwersytet w Białymstoku',
  'Uniwersytet Warmińsko-Mazurski w Olsztynie',
  'Uniwersytet Warszawski',
  'Uniwersytet Wrocławski',
  'Uniwersytet Zielonogórski',
  'VIAMODA Szkoła Wyższa z siedzibą w Warszawie',
  'Warszawska Szkoła Filmowa z siedzibą w Warszawie',
  'Warszawska Szkoła Zarządzania - Szkoła Wyższa w Warszawie',
  'Warszawski Uniwersytet Medyczny',
  'Wielkopolskie Centrum Onkologii im. Marii Skłodowskiej-Curie',
  'Wojewódzki Szpital Specjalistyczny we Wrocławiu',
  'Wojskowa Akademia Techniczna im. Jarosława Dąbrowskiego',
  'Wojskowy Instytut Chemii i Radiometrii',
  'Wojskowy Instytut Medycyny Lotniczej',
  'Wojskowy Instytut Higieny i Epidemiologii im. gen. Karola Kaczkowskiego',
  'Wojskowy Instytut Techniczny Uzbrojenia',
  'Wojskowy Instytut Techniki Inżynieryjnej im. profesora Józefa Kosackiego',
  'Wojskowy Instytut Techniki Pancernej i Samochodowej',
  'Wyższa Inżynierska Szkoła Bezpieczeństwa i Organizacji Pracy w Radomiu',
  'Wyższa Szkoła - Edukacja w Sporcie w Warszawie',
  'Wyższa Szkoła Administracji i Biznesu im. Eugeniusza Kwiatkowskiego w Gdyni',
  'Wyższa Szkoła Administracji Publicznej w Kielcach',
  'Wyższa Szkoła Administracji Publicznej w Ostrołęce',
  'Wyższa Szkoła Administracji w Bielsku-Białej',
  'Wyższa Szkoła Artystyczna w Warszawie',
  'Wyższa Szkoła Bezpieczeństwa w Poznaniu',
  'Wyższa Szkoła Biznesu i Nauk o Zdrowiu w Łodzi',
  'Wyższa Szkoła Biznesu w Gorzowie Wlkp.',
  'Wyższa Szkoła COSINUS w Łodzi',
  'Wyższa Szkoła Ekonomiczna w Białymstoku',
  'Wyższa Szkoła Ekonomiczno-Humanistyczna w Bielsku-Białej',
  'Wyższa Szkoła Ekonomii i Informatyki w Krakowie',
  'Wyższa Szkoła Finansów i Informatyki im. prof. Janusza Chechlińskiego w Łodzi',
  'Wyższa Szkoła Fizjoterapii we Wrocławiu',
  'Wyższa Szkoła Gospodarki w Bydgoszczy',
  'Wyższa Szkoła Humanistyczna im. Króla Stanisława Leszczyńskiego w Lesznie',
  'Wyższa Szkoła Humanistyczna we Wrocławiu',
  'Wyższa Szkoła Humanistyczno-Ekonomiczna im. J. Zamoyskiego w Zamościu',
  'Wyższa Szkoła Humanistyczno-Ekonomiczna w Brzegu',
  'Wyższa Szkoła Humanistyczno-Przyrodnicza Studium Generale Sandomiriense w Sandomierzu',
  'Wyższa Szkoła Informatyki i Zarządzania w Bielsku-Białej',
  'Wyższa Szkoła Informatyki i Zarządzania z siedzibą w Rzeszowie',
  'Wyższa Szkoła Integracji Europejskiej w Szczecinie',
  'Wyższa Szkoła Inżynierii Gospodarki w Słupsku',
  'Wyższa Szkoła Języków Obcych im. Samuela Bogumiła Lindego z siedzibą w Poznaniu',
  'Wyższa Szkoła Komunikacji Społecznej w Gdyni',
  'Wyższa Szkoła Kosmetyki i Nauk o Zdrowiu w Łodzi',
  'Wyższa Szkoła Lingwistyczna w Częstochowie',
  'Wyższa Szkoła Logistyki w Poznaniu',
  'Wyższa Szkoła Medyczna w Legnicy z siedzibą w Legnicy',
  'Wyższa Szkoła Medyczna w Sosnowcu',
  'Wyższa Szkoła Medyczna z siedzibą w Białymstoku',
  'Wyższa Szkoła Nauk Medycznych w Warszawie',
  'Wyższa Szkoła Nauk o Zdrowiu w Bydgoszczy',
  'Wyższa Szkoła Nauk Stosowanych w Rudzie Śląskiej',
  'Wyższa Szkoła Pedagogiczno-Techniczna w Koninie',
  'Wyższa Szkoła Planowania Strategicznego w Dąbrowie Górniczej',
  'Wyższa Szkoła Przedsiębiorczości i Administracji w Lublinie',
  'Wyższa Szkoła Stosunków Międzynarodowych i Amerykanistyki w Warszawie',
  'Wyższa Szkoła Straży Granicznej',
  'Wyższa Szkoła Sztuki i Projektowania w Łodzi',
  'Wyższa Szkoła Technologii Informatycznych w Katowicach',
  'Wyższa Szkoła Teologiczno-Humanistyczna im. Michała Beliny-Czechowskiego w Podkowie Leśnej',
  'Wyższa Szkoła Teologiczno–Społeczna w Warszawie',
  'Wyższa Szkoła Turystyki i Ekologii w Suchej Beskidzkiej',
  'Wyższa Szkoła Turystyki i Hotelarstwa w Gdańsku',
  'Wyższa Szkoła Turystyki i Języków Obcych w Warszawie',
  'Wyższa Szkoła Umiejętności Zawodowych w Pińczowie',
  'Wyższa Szkoła Współpracy Międzynarodowej i Regionalnej im. Zygmunta Glogera z siedzibą w Wołominie',
  'Wyższa Szkoła Zarządzania "Edukacja" we Wrocławiu',
  'Wyższa Szkoła Zarządzania i Bankowości w Krakowie',
  'Wyższa Szkoła Zarządzania Ochroną Pracy w Katowicach',
  'Wyższa Szkoła Zarządzania Środowiskiem w Tucholi',
  'Wyższa Szkoła Zarządzania w Częstochowie',
  'Wyższa Szkoła Zawodowa Ochrony Zdrowia TWP w Łomży z siedzibą w Łomży',
  'Wyższa Szkoła Zdrowia, Urody i Edukacji w Poznaniu',
  'Wyższe Baptystyczne Seminarium Teologiczne w Warszawie',
  'Wyższe Seminarium Duchowne Diecezji Pelplińskiej',
  'Wyższe Seminarium Duchowne Kościoła Polskokatolickiego w Warszawie',
  'Wyższe Seminarium Duchowne Towarzystwa Salezjańskiego w Lądzie',
  'Wyższe Seminarium Duchowne w Przemyślu',
  'Wyższe Seminarium Duchowne w Rzeszowie',
  'Wyższe Seminarium Teologiczne imienia Jana Łaskiego w Warszawie',
  'Wyższy Instytut Teologiczny w Częstochowie',
  'Zachodniopomorski Uniwersytet Technologiczny w Szczecinie',
  'Akademia Muzyczna im. Grażyny i Kiejstuta Bacewiczów w Łodzi',
  'Akademia Leona Koźmińskiego w Warszawie',
  'Akademia Marynarki Wojennej im. Bohaterów Westerplatte',
];

const data = universities.map((name) => ({ name }));

async function main() {
  await prisma.university.createMany({ data, skipDuplicates: true });
  console.log(`Seeded ${data.length} universities (skipDuplicates on).`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
